//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sitecore.Feature.Scaffolding.Models {
    
    
    /// <summary>Represents the /sitecore/templates/Feature/Scaffolding/Main Navigation Settings template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "9.1")]
    [Synthesis.Synchronization.RepresentsSitecoreTemplateAttribute("{013261F6-378B-4750-9980-7DCB9991BF9E}", "9Pgico55eM/qj1n5NvjbUsf4fZ8=", "Sitecore.Feature.Scaffolding")]
    public partial interface IMainNavigationSettingsItem : global::Sitecore.Foundation.BaseSite.Models.I_BaseStandardTemplateItem {
        
        /// <summary>Represents the Icon Text field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("icon_text")]
        Synthesis.FieldTypes.Interfaces.ITextField IconText {
            get;
        }
    }
}

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sitecore.Feature.Scaffolding.Models.Concrete {
    
    
    /// <summary>Represents the /sitecore/templates/Feature/Scaffolding/Main Navigation Settings template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "9.1")]
    public partial class MainNavigationSettings : global::Synthesis.StandardTemplateItem, global::Sitecore.Feature.Scaffolding.Models.IMainNavigationSettingsItem {
        
        private Synthesis.FieldTypes.TextField _iconText;
        
        public MainNavigationSettings(Sitecore.Data.Items.Item innerItem) : 
                base(innerItem) {
        }
        
        public MainNavigationSettings(global::System.Collections.Generic.IDictionary<string, string> searchFields) : 
                base(searchFields) {
        }
        
        /// <summary>The name of the Sitecore Template that this class represents</summary>
        public static string TemplateName {
            get {
                return "Main Navigation Settings";
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public static Sitecore.Data.ID ItemTemplateId {
            get {
                return new Sitecore.Data.ID("{013261F6-378B-4750-9980-7DCB9991BF9E}");
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public override Sitecore.Data.ID TemplateId {
            get {
                return ItemTemplateId;
            }
        }
        
        /// <summary>Represents the Icon Text field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("icon_text")]
        public Synthesis.FieldTypes.Interfaces.ITextField IconText {
            get {
                if (_iconText == null) {
                    _iconText = new Synthesis.FieldTypes.TextField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{379AFB4F-BEBF-41A8-AFB4-EFCEB768924B}"], "/sitecore/templates/Feature/Scaffolding/Main Navigation Settings", "Icon Text"), this.GetSearchFieldValue("icon_text"));
                }
                return _iconText;
            }
        }
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "9.1")]
    public class MainNavigationSettingsInitializer : Synthesis.Initializers.ITemplateInitializer {
        
        public Sitecore.Data.ID InitializesTemplateId {
            get {
                return new Sitecore.Data.ID("{013261F6-378B-4750-9980-7DCB9991BF9E}");
            }
        }
        
        public Synthesis.IStandardTemplateItem CreateInstance(Sitecore.Data.Items.Item innerItem) {
            return new MainNavigationSettings(innerItem);
        }
        
        public Synthesis.IStandardTemplateItem CreateInstanceFromSearch(global::System.Collections.Generic.IDictionary<string, string> searchFields) {
            return new MainNavigationSettings(searchFields);
        }
    }
}
