//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sitecore.Feature.Media.Models {
    
    
    /// <summary>Represents the /sitecore/templates/Feature/Media/Carousel Settings template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "9.1")]
    [Synthesis.Synchronization.RepresentsSitecoreTemplateAttribute("{AF2C6BEC-5346-4D3F-B752-65FA70F02C37}", "+jJkwInSS5PQ1c7SkucaJ9lHypw=", "Sitecore.Feature.Media")]
    public partial interface ICarouselSettingsItem : global::Sitecore.Foundation.BaseSite.Models.I_BaseStandardTemplateItem {
        
        /// <summary>Represents the Left Text field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("left_text")]
        Synthesis.FieldTypes.Interfaces.ITextField LeftText {
            get;
        }
        
        /// <summary>Represents the Right Text field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("right_text")]
        Synthesis.FieldTypes.Interfaces.ITextField RightText {
            get;
        }
    }
    
    /// <summary>Represents the /sitecore/templates/Feature/Media/Carousel Slide template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "9.1")]
    [Synthesis.Synchronization.RepresentsSitecoreTemplateAttribute("{8B2B1A2E-B230-46BA-AE6F-51F6C03E110C}", "s/5PavOTuGdTkHLQBbWvPdjUyEE=", "Sitecore.Feature.Media")]
    public partial interface ICarouselSlideItem : global::Sitecore.Foundation.BaseSite.Models.I_BaseStandardTemplateItem {
        
        /// <summary>Represents the Slide Image field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("slide_image")]
        Synthesis.FieldTypes.Interfaces.IImageField SlideImage {
            get;
        }
    }
}

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sitecore.Feature.Media.Models.Concrete {
    
    
    /// <summary>Represents the /sitecore/templates/Feature/Media/Carousel Settings template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "9.1")]
    public partial class CarouselSettings : global::Synthesis.StandardTemplateItem, global::Sitecore.Feature.Media.Models.ICarouselSettingsItem {
        
        private Synthesis.FieldTypes.TextField _leftText;
        
        private Synthesis.FieldTypes.TextField _rightText;
        
        public CarouselSettings(Sitecore.Data.Items.Item innerItem) : 
                base(innerItem) {
        }
        
        public CarouselSettings(global::System.Collections.Generic.IDictionary<string, string> searchFields) : 
                base(searchFields) {
        }
        
        /// <summary>The name of the Sitecore Template that this class represents</summary>
        public static string TemplateName {
            get {
                return "Carousel Settings";
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public static Sitecore.Data.ID ItemTemplateId {
            get {
                return new Sitecore.Data.ID("{AF2C6BEC-5346-4D3F-B752-65FA70F02C37}");
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public override Sitecore.Data.ID TemplateId {
            get {
                return ItemTemplateId;
            }
        }
        
        /// <summary>Represents the Left Text field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("left_text")]
        public Synthesis.FieldTypes.Interfaces.ITextField LeftText {
            get {
                if (_leftText == null) {
                    _leftText = new Synthesis.FieldTypes.TextField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{19734D94-F3EB-47C1-8BFD-EFE2C3CE3C7C}"], "/sitecore/templates/Feature/Media/Carousel Settings", "Left Text"), this.GetSearchFieldValue("left_text"));
                }
                return _leftText;
            }
        }
        
        /// <summary>Represents the Right Text field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("right_text")]
        public Synthesis.FieldTypes.Interfaces.ITextField RightText {
            get {
                if (_rightText == null) {
                    _rightText = new Synthesis.FieldTypes.TextField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{75CA831E-B3A6-4430-8A6B-6C79552E9C04}"], "/sitecore/templates/Feature/Media/Carousel Settings", "Right Text"), this.GetSearchFieldValue("right_text"));
                }
                return _rightText;
            }
        }
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "9.1")]
    public class CarouselSettingsInitializer : Synthesis.Initializers.ITemplateInitializer {
        
        public Sitecore.Data.ID InitializesTemplateId {
            get {
                return new Sitecore.Data.ID("{AF2C6BEC-5346-4D3F-B752-65FA70F02C37}");
            }
        }
        
        public Synthesis.IStandardTemplateItem CreateInstance(Sitecore.Data.Items.Item innerItem) {
            return new CarouselSettings(innerItem);
        }
        
        public Synthesis.IStandardTemplateItem CreateInstanceFromSearch(global::System.Collections.Generic.IDictionary<string, string> searchFields) {
            return new CarouselSettings(searchFields);
        }
    }
    
    /// <summary>Represents the /sitecore/templates/Feature/Media/Carousel Slide template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "9.1")]
    public partial class CarouselSlide : global::Synthesis.StandardTemplateItem, global::Sitecore.Feature.Media.Models.ICarouselSlideItem {
        
        private Synthesis.FieldTypes.ImageField _slideImage;
        
        public CarouselSlide(Sitecore.Data.Items.Item innerItem) : 
                base(innerItem) {
        }
        
        public CarouselSlide(global::System.Collections.Generic.IDictionary<string, string> searchFields) : 
                base(searchFields) {
        }
        
        /// <summary>The name of the Sitecore Template that this class represents</summary>
        public static string TemplateName {
            get {
                return "Carousel Slide";
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public static Sitecore.Data.ID ItemTemplateId {
            get {
                return new Sitecore.Data.ID("{8B2B1A2E-B230-46BA-AE6F-51F6C03E110C}");
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public override Sitecore.Data.ID TemplateId {
            get {
                return ItemTemplateId;
            }
        }
        
        /// <summary>Represents the Slide Image field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("slide_image")]
        public Synthesis.FieldTypes.Interfaces.IImageField SlideImage {
            get {
                if (_slideImage == null) {
                    _slideImage = new Synthesis.FieldTypes.ImageField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{9DDDF327-9BA7-40B9-8121-F1AEDD63F8F7}"], "/sitecore/templates/Feature/Media/Carousel Slide", "Slide Image"), this.GetSearchFieldValue("slide_image"));
                }
                return _slideImage;
            }
        }
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "9.1")]
    public class CarouselSlideInitializer : Synthesis.Initializers.ITemplateInitializer {
        
        public Sitecore.Data.ID InitializesTemplateId {
            get {
                return new Sitecore.Data.ID("{8B2B1A2E-B230-46BA-AE6F-51F6C03E110C}");
            }
        }
        
        public Synthesis.IStandardTemplateItem CreateInstance(Sitecore.Data.Items.Item innerItem) {
            return new CarouselSlide(innerItem);
        }
        
        public Synthesis.IStandardTemplateItem CreateInstanceFromSearch(global::System.Collections.Generic.IDictionary<string, string> searchFields) {
            return new CarouselSlide(searchFields);
        }
    }
}
