//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sitecore.Foundation.BaseSite.Models {
    
    
    /// <summary>Represents the /sitecore/templates/Foundation/BaseSite/Navigation Item template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "9.1")]
    [Synthesis.Synchronization.RepresentsSitecoreTemplateAttribute("{F7D70504-4379-48EA-8105-CEB5184C754F}", "MkpykvMP9xuBrzxTrLaNFuyXY2M=", "Sitecore.Foundation.BaseSite")]
    public partial interface INavigationItemItem : global::Sitecore.Foundation.BaseSite.Models.I_BaseStandardTemplateItem {
        
        /// <summary>Represents the Link field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("link")]
        Synthesis.FieldTypes.Interfaces.IHyperlinkField Link {
            get;
        }
        
        /// <summary>Represents the Link Text field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("link_text")]
        Synthesis.FieldTypes.Interfaces.ITextField LinkText {
            get;
        }
    }
    
    /// <summary>Represents the /sitecore/templates/Foundation/BaseSite/_Base Site Root template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "9.1")]
    [Synthesis.Synchronization.RepresentsSitecoreTemplateAttribute("{250C92DD-2269-45C7-B058-6506E488365A}", "X6sL7aZ02gVnKTvQpOa8bU1gZWQ=", "Sitecore.Foundation.BaseSite")]
    public partial interface I_BaseSiteRootItem : global::Sitecore.Foundation.BaseSite.Models.I_BaseStandardTemplateItem {
    }
    
    /// <summary>Represents the /sitecore/templates/Foundation/BaseSite/_Base Standard Template template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "9.1")]
    [Synthesis.Synchronization.RepresentsSitecoreTemplateAttribute("{15E60B57-A4FD-4381-8983-5E704F6D39F9}", "FV4vKqBz6mxgXmrmbpww4II9SP8=", "Sitecore.Foundation.BaseSite")]
    public partial interface I_BaseStandardTemplateItem : Synthesis.IStandardTemplateItem {
    }
    
    /// <summary>Represents the /sitecore/templates/Foundation/BaseSite/_Base Web Page template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "9.1")]
    [Synthesis.Synchronization.RepresentsSitecoreTemplateAttribute("{901A8283-DA77-4B74-9C12-A7EC611B8658}", "v24/wY00NA2yg9JOmVMzjLaEQ1E=", "Sitecore.Foundation.BaseSite")]
    public partial interface I_BaseWebPageItem : global::Sitecore.Foundation.BaseSite.Models.I_BaseStandardTemplateItem {
    }
}

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sitecore.Foundation.BaseSite.Models.Concrete {
    
    
    /// <summary>Represents the /sitecore/templates/Foundation/BaseSite/Navigation Item template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "9.1")]
    public partial class NavigationItem : global::Synthesis.StandardTemplateItem, global::Sitecore.Foundation.BaseSite.Models.INavigationItemItem {
        
        private Synthesis.FieldTypes.HyperlinkField _link;
        
        private Synthesis.FieldTypes.TextField _linkText;
        
        public NavigationItem(Sitecore.Data.Items.Item innerItem) : 
                base(innerItem) {
        }
        
        public NavigationItem(global::System.Collections.Generic.IDictionary<string, string> searchFields) : 
                base(searchFields) {
        }
        
        /// <summary>The name of the Sitecore Template that this class represents</summary>
        public static string TemplateName {
            get {
                return "Navigation Item";
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public static Sitecore.Data.ID ItemTemplateId {
            get {
                return new Sitecore.Data.ID("{F7D70504-4379-48EA-8105-CEB5184C754F}");
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public override Sitecore.Data.ID TemplateId {
            get {
                return ItemTemplateId;
            }
        }
        
        /// <summary>Represents the Link field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("link")]
        public Synthesis.FieldTypes.Interfaces.IHyperlinkField Link {
            get {
                if (_link == null) {
                    _link = new Synthesis.FieldTypes.HyperlinkField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{9E7D7B9B-C87B-407E-8624-F6BD15E53A9A}"], "/sitecore/templates/Foundation/BaseSite/Navigation Item", "Link"), this.GetSearchFieldValue("link"));
                }
                return _link;
            }
        }
        
        /// <summary>Represents the Link Text field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("link_text")]
        public Synthesis.FieldTypes.Interfaces.ITextField LinkText {
            get {
                if (_linkText == null) {
                    _linkText = new Synthesis.FieldTypes.TextField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{BF621C36-9F8B-4CE4-8B82-FF2E8A4978CE}"], "/sitecore/templates/Foundation/BaseSite/Navigation Item", "Link Text"), this.GetSearchFieldValue("link_text"));
                }
                return _linkText;
            }
        }
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "9.1")]
    public class NavigationItemInitializer : Synthesis.Initializers.ITemplateInitializer {
        
        public Sitecore.Data.ID InitializesTemplateId {
            get {
                return new Sitecore.Data.ID("{F7D70504-4379-48EA-8105-CEB5184C754F}");
            }
        }
        
        public Synthesis.IStandardTemplateItem CreateInstance(Sitecore.Data.Items.Item innerItem) {
            return new NavigationItem(innerItem);
        }
        
        public Synthesis.IStandardTemplateItem CreateInstanceFromSearch(global::System.Collections.Generic.IDictionary<string, string> searchFields) {
            return new NavigationItem(searchFields);
        }
    }
    
    /// <summary>Represents the /sitecore/templates/Foundation/BaseSite/_Base Site Root template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "9.1")]
    public partial class _BaseSiteRoot : global::Synthesis.StandardTemplateItem, global::Sitecore.Foundation.BaseSite.Models.I_BaseSiteRootItem {
        
        public _BaseSiteRoot(Sitecore.Data.Items.Item innerItem) : 
                base(innerItem) {
        }
        
        public _BaseSiteRoot(global::System.Collections.Generic.IDictionary<string, string> searchFields) : 
                base(searchFields) {
        }
        
        /// <summary>The name of the Sitecore Template that this class represents</summary>
        public static string TemplateName {
            get {
                return "_Base Site Root";
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public static Sitecore.Data.ID ItemTemplateId {
            get {
                return new Sitecore.Data.ID("{250C92DD-2269-45C7-B058-6506E488365A}");
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public override Sitecore.Data.ID TemplateId {
            get {
                return ItemTemplateId;
            }
        }
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "9.1")]
    public class _BaseSiteRootInitializer : Synthesis.Initializers.ITemplateInitializer {
        
        public Sitecore.Data.ID InitializesTemplateId {
            get {
                return new Sitecore.Data.ID("{250C92DD-2269-45C7-B058-6506E488365A}");
            }
        }
        
        public Synthesis.IStandardTemplateItem CreateInstance(Sitecore.Data.Items.Item innerItem) {
            return new _BaseSiteRoot(innerItem);
        }
        
        public Synthesis.IStandardTemplateItem CreateInstanceFromSearch(global::System.Collections.Generic.IDictionary<string, string> searchFields) {
            return new _BaseSiteRoot(searchFields);
        }
    }
    
    /// <summary>Represents the /sitecore/templates/Foundation/BaseSite/_Base Standard Template template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "9.1")]
    public partial class _BaseStandardTemplate : global::Synthesis.StandardTemplateItem, global::Sitecore.Foundation.BaseSite.Models.I_BaseStandardTemplateItem {
        
        public _BaseStandardTemplate(Sitecore.Data.Items.Item innerItem) : 
                base(innerItem) {
        }
        
        public _BaseStandardTemplate(global::System.Collections.Generic.IDictionary<string, string> searchFields) : 
                base(searchFields) {
        }
        
        /// <summary>The name of the Sitecore Template that this class represents</summary>
        public static string TemplateName {
            get {
                return "_Base Standard Template";
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public static Sitecore.Data.ID ItemTemplateId {
            get {
                return new Sitecore.Data.ID("{15E60B57-A4FD-4381-8983-5E704F6D39F9}");
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public override Sitecore.Data.ID TemplateId {
            get {
                return ItemTemplateId;
            }
        }
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "9.1")]
    public class _BaseStandardTemplateInitializer : Synthesis.Initializers.ITemplateInitializer {
        
        public Sitecore.Data.ID InitializesTemplateId {
            get {
                return new Sitecore.Data.ID("{15E60B57-A4FD-4381-8983-5E704F6D39F9}");
            }
        }
        
        public Synthesis.IStandardTemplateItem CreateInstance(Sitecore.Data.Items.Item innerItem) {
            return new _BaseStandardTemplate(innerItem);
        }
        
        public Synthesis.IStandardTemplateItem CreateInstanceFromSearch(global::System.Collections.Generic.IDictionary<string, string> searchFields) {
            return new _BaseStandardTemplate(searchFields);
        }
    }
    
    /// <summary>Represents the /sitecore/templates/Foundation/BaseSite/_Base Web Page template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "9.1")]
    public partial class _BaseWebPage : global::Synthesis.StandardTemplateItem, global::Sitecore.Foundation.BaseSite.Models.I_BaseWebPageItem {
        
        public _BaseWebPage(Sitecore.Data.Items.Item innerItem) : 
                base(innerItem) {
        }
        
        public _BaseWebPage(global::System.Collections.Generic.IDictionary<string, string> searchFields) : 
                base(searchFields) {
        }
        
        /// <summary>The name of the Sitecore Template that this class represents</summary>
        public static string TemplateName {
            get {
                return "_Base Web Page";
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public static Sitecore.Data.ID ItemTemplateId {
            get {
                return new Sitecore.Data.ID("{901A8283-DA77-4B74-9C12-A7EC611B8658}");
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public override Sitecore.Data.ID TemplateId {
            get {
                return ItemTemplateId;
            }
        }
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "9.1")]
    public class _BaseWebPageInitializer : Synthesis.Initializers.ITemplateInitializer {
        
        public Sitecore.Data.ID InitializesTemplateId {
            get {
                return new Sitecore.Data.ID("{901A8283-DA77-4B74-9C12-A7EC611B8658}");
            }
        }
        
        public Synthesis.IStandardTemplateItem CreateInstance(Sitecore.Data.Items.Item innerItem) {
            return new _BaseWebPage(innerItem);
        }
        
        public Synthesis.IStandardTemplateItem CreateInstanceFromSearch(global::System.Collections.Generic.IDictionary<string, string> searchFields) {
            return new _BaseWebPage(searchFields);
        }
    }
}
