//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sitecore.Foundation.DataAccess.Models {
    
    
    /// <summary>Represents the /sitecore/templates/System/Layout/Rendering Parameters/Standard Rendering Parameters template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "9.0")]
    [Synthesis.Synchronization.RepresentsSitecoreTemplateAttribute("{8CA06D6A-B353-44E8-BC31-B528C7306971}", "+RZeWmK0ydsXKI4jJuRJFeMBt18=", "Sitecore.Foundation.DataAccess")]
    public partial interface IStandardRenderingParametersItem : Synthesis.IStandardTemplateItem {
        
        /// <summary>Represents the Caching field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("caching")]
        Synthesis.FieldTypes.Interfaces.ITextField Caching {
            get;
        }
        
        /// <summary>Represents the Personalization field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("personalization")]
        Synthesis.FieldTypes.Interfaces.ITextField Personalization {
            get;
        }
        
        /// <summary>Represents the Placeholder field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("placeholder")]
        Synthesis.FieldTypes.Interfaces.ITextField Placeholder {
            get;
        }
        
        /// <summary>Represents the Tests field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("tests")]
        Sitecore.Foundation.DataAccess.FieldTypes.IHelixItemReferenceField Tests {
            get;
        }
        
        /// <summary>Represents the Data Source field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("data_source")]
        Synthesis.FieldTypes.Interfaces.ITextField DataSource {
            get;
        }
        
        /// <summary>Represents the Additional Parameters field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("additional_parameters")]
        Synthesis.FieldTypes.Interfaces.IDictionaryField AdditionalParameters {
            get;
        }
    }
    
    /// <summary>Represents the /sitecore/templates/Foundation/DataAccess/_Base Standard Rendering Parameters template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "9.0")]
    [Synthesis.Synchronization.RepresentsSitecoreTemplateAttribute("{C7705CA8-0834-4ECC-A97F-732756C9449C}", "r4DRftGVNjBrcSGjrDSQurANCFs=", "Sitecore.Foundation.DataAccess")]
    public partial interface I_BaseStandardRenderingParametersItem : global::Sitecore.Foundation.DataAccess.Models.IStandardRenderingParametersItem {
    }
    
    /// <summary>Represents the /sitecore/templates/Foundation/DataAccess/_Base Standard Template template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "9.0")]
    [Synthesis.Synchronization.RepresentsSitecoreTemplateAttribute("{8C0CBC69-F633-4CD0-A863-7620B7819BB1}", "pP8Q5CjTlVpvqg09Q4sEp09sw2c=", "Sitecore.Foundation.DataAccess")]
    public partial interface I_BaseStandardTemplateItem : Synthesis.IStandardTemplateItem {
    }
}

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sitecore.Foundation.DataAccess.Models.Concrete {
    
    
    /// <summary>Represents the /sitecore/templates/Foundation/DataAccess/_Base Standard Rendering Parameters template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "9.0")]
    public partial class _BaseStandardRenderingParameters : global::Synthesis.StandardTemplateItem, global::Sitecore.Foundation.DataAccess.Models.I_BaseStandardRenderingParametersItem {
        
        private Synthesis.FieldTypes.TextField _caching;
        
        private Synthesis.FieldTypes.TextField _personalization;
        
        private Synthesis.FieldTypes.TextField _placeholder;
        
        private Sitecore.Foundation.DataAccess.FieldTypes.HelixItemReferenceField _tests;
        
        private Synthesis.FieldTypes.TextField _dataSource;
        
        private Synthesis.FieldTypes.DictionaryField _additionalParameters;
        
        public _BaseStandardRenderingParameters(Sitecore.Data.Items.Item innerItem) : 
                base(innerItem) {
        }
        
        public _BaseStandardRenderingParameters(global::System.Collections.Generic.IDictionary<string, string> searchFields) : 
                base(searchFields) {
        }
        
        /// <summary>The name of the Sitecore Template that this class represents</summary>
        public static string TemplateName {
            get {
                return "_Base Standard Rendering Parameters";
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public static Sitecore.Data.ID ItemTemplateId {
            get {
                return new Sitecore.Data.ID("{C7705CA8-0834-4ECC-A97F-732756C9449C}");
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public override Sitecore.Data.ID TemplateId {
            get {
                return ItemTemplateId;
            }
        }
        
        /// <summary>Represents the Caching field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("caching")]
        public Synthesis.FieldTypes.Interfaces.ITextField Caching {
            get {
                if (_caching == null) {
                    _caching = new Synthesis.FieldTypes.TextField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{3094D236-5985-4C4F-AE6A-E30740885532}"], "/sitecore/templates/Foundation/DataAccess/_Base Standard Rendering Parameters", "Caching"), this.GetSearchFieldValue("caching"));
                }
                return _caching;
            }
        }
        
        /// <summary>Represents the Personalization field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("personalization")]
        public Synthesis.FieldTypes.Interfaces.ITextField Personalization {
            get {
                if (_personalization == null) {
                    _personalization = new Synthesis.FieldTypes.TextField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{C502BDEB-F5DA-4AD0-8095-D7CC1D0E1EEC}"], "/sitecore/templates/Foundation/DataAccess/_Base Standard Rendering Parameters", "Personalization"), this.GetSearchFieldValue("personalization"));
                }
                return _personalization;
            }
        }
        
        /// <summary>Represents the Placeholder field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("placeholder")]
        public Synthesis.FieldTypes.Interfaces.ITextField Placeholder {
            get {
                if (_placeholder == null) {
                    _placeholder = new Synthesis.FieldTypes.TextField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{E42027F4-766D-45A7-8CF4-29E5C94326F7}"], "/sitecore/templates/Foundation/DataAccess/_Base Standard Rendering Parameters", "Placeholder"), this.GetSearchFieldValue("placeholder"));
                }
                return _placeholder;
            }
        }
        
        /// <summary>Represents the Tests field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("tests")]
        public Sitecore.Foundation.DataAccess.FieldTypes.IHelixItemReferenceField Tests {
            get {
                if (_tests == null) {
                    _tests = new Sitecore.Foundation.DataAccess.FieldTypes.HelixItemReferenceField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{0FA4635B-8BF4-46DF-994D-621B76F0A7AD}"], "/sitecore/templates/Foundation/DataAccess/_Base Standard Rendering Parameters", "Tests"), this.GetSearchFieldValue("tests"));
                }
                return _tests;
            }
        }
        
        /// <summary>Represents the Data Source field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("data_source")]
        public Synthesis.FieldTypes.Interfaces.ITextField DataSource {
            get {
                if (_dataSource == null) {
                    _dataSource = new Synthesis.FieldTypes.TextField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{0793DCFF-0EE7-48AD-B9D4-EF1DD24EB59B}"], "/sitecore/templates/Foundation/DataAccess/_Base Standard Rendering Parameters", "Data Source"), this.GetSearchFieldValue("data_source"));
                }
                return _dataSource;
            }
        }
        
        /// <summary>Represents the Additional Parameters field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("additional_parameters")]
        public Synthesis.FieldTypes.Interfaces.IDictionaryField AdditionalParameters {
            get {
                if (_additionalParameters == null) {
                    _additionalParameters = new Synthesis.FieldTypes.DictionaryField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{485E33D4-79F1-428F-8258-2CB29BB7CC6B}"], "/sitecore/templates/Foundation/DataAccess/_Base Standard Rendering Parameters", "Additional Parameters"), this.GetSearchFieldValue("additional_parameters"));
                }
                return _additionalParameters;
            }
        }
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "9.0")]
    public class _BaseStandardRenderingParametersInitializer : Synthesis.Initializers.ITemplateInitializer {
        
        public Sitecore.Data.ID InitializesTemplateId {
            get {
                return new Sitecore.Data.ID("{C7705CA8-0834-4ECC-A97F-732756C9449C}");
            }
        }
        
        public Synthesis.IStandardTemplateItem CreateInstance(Sitecore.Data.Items.Item innerItem) {
            return new _BaseStandardRenderingParameters(innerItem);
        }
        
        public Synthesis.IStandardTemplateItem CreateInstanceFromSearch(global::System.Collections.Generic.IDictionary<string, string> searchFields) {
            return new _BaseStandardRenderingParameters(searchFields);
        }
    }
    
    /// <summary>Represents the /sitecore/templates/Foundation/DataAccess/_Base Standard Template template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "9.0")]
    public partial class _BaseStandardTemplate : global::Synthesis.StandardTemplateItem, global::Sitecore.Foundation.DataAccess.Models.I_BaseStandardTemplateItem {
        
        public _BaseStandardTemplate(Sitecore.Data.Items.Item innerItem) : 
                base(innerItem) {
        }
        
        public _BaseStandardTemplate(global::System.Collections.Generic.IDictionary<string, string> searchFields) : 
                base(searchFields) {
        }
        
        /// <summary>The name of the Sitecore Template that this class represents</summary>
        public static string TemplateName {
            get {
                return "_Base Standard Template";
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public static Sitecore.Data.ID ItemTemplateId {
            get {
                return new Sitecore.Data.ID("{8C0CBC69-F633-4CD0-A863-7620B7819BB1}");
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public override Sitecore.Data.ID TemplateId {
            get {
                return ItemTemplateId;
            }
        }
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "9.0")]
    public class _BaseStandardTemplateInitializer : Synthesis.Initializers.ITemplateInitializer {
        
        public Sitecore.Data.ID InitializesTemplateId {
            get {
                return new Sitecore.Data.ID("{8C0CBC69-F633-4CD0-A863-7620B7819BB1}");
            }
        }
        
        public Synthesis.IStandardTemplateItem CreateInstance(Sitecore.Data.Items.Item innerItem) {
            return new _BaseStandardTemplate(innerItem);
        }
        
        public Synthesis.IStandardTemplateItem CreateInstanceFromSearch(global::System.Collections.Generic.IDictionary<string, string> searchFields) {
            return new _BaseStandardTemplate(searchFields);
        }
    }
}
